apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-one
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  minReadySeconds: 30
  selector:
    matchLabels:
      app: spring-one
  template:
    metadata:
      labels:
        app: spring-one
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - service
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - service
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      containers:
        - name: spring-one
          image: registry.cmri.cn/znm/spring-one:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4Gi"
              cpu: "200m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          ports:
            - containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: admin
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: admin
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: "/actuator/startup"
              port: admin
            initialDelaySeconds: 15
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: NACOS_CONFIG_GROUPID
              value: DEFAULT_GROUP
            - name: NACOS_CONFIG_SERVER
              value: nacos-headless.default.svc:8848
            - name: NACOS_DISCOVERY_SERVER
              value: nacos-headless.default.svc:8848
---
apiVersion: v1
kind: Service
metadata:
  name: spring-one-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-one
