server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    root: INFO

management:
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
    startup:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,startup
