server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 5m

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

management:
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
    startup:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,startup,deregister
